Repository mobileappdevhm/dev-team-1-cie-app-in-flutter, pull requests merged in 2018-06, with the labels that each got.

#97 Fix blue page that appears to have survived the timetable merge
  lib/views/tabs.dart
Labels: bug

#95 Add alert functionality to course submission button on favorites page
  lib/generic/genericAlert.dart
  lib/utils/staticVariables.dart
  lib/widgets/courseList.dart
Labels: enhancement

#99 Mock update to show conflicts in sprint 2 presentation
  lib/model/course/courses_mock.dart
  lib/model/user/currentUser_mock.dart
Labels: in progress

#102 F_login
  lib/views/login.dart
Labels: in progress

#120 improved testing
  test/views/tab_test.dart
Labels: bug

#159 Fix time conflict detection and made more modular
  lib/utils/schedulingUtility.dart
  lib/utils/staticVariables.dart
  lib/views/schedule.dart
  test/utils/schedulingUtility_test.dart
Labels: bug

#160 Add builder tests
  test/model/course/course_test.dart
Labels: enhancement

#162 Json user settings data
  lib/di/currentUser_di.dart
  lib/model/course/course.dart
  lib/model/user/currentUser_mock.dart
  lib/model/user/currentUser_prod.dart
  lib/model/user/user.dart
  lib/presenter/courseListPresenter.dart
  lib/presenter/currentUserPresenter.dart
  lib/presenter/timeTablePresenter.dart
  lib/utils/cieStyle.dart
  lib/utils/fileStore.dart
  lib/utils/staticVariables.dart
  lib/views/login.dart
  lib/views/schedule.dart
  lib/views/settings.dart
  lib/views/tabs.dart
  lib/views/takenCourses.dart
  lib/widgets/courseDetails.dart
  lib/widgets/courseList.dart
  test/model/user/user_test.dart
  test/presenter/currentUserPresenter_test.dart
  test/views/settings_test.dart
Labels: enhancement

#176 Match update pull down color with the blue used elsewhere in the application
  lib/widgets/courseList.dart
Labels: enhancement

#197 Just a simple change. Changing to ShowDialog would need to much effor…
  lib/widgets/courseList.dart
Labels: in progress

#198 Fix crash from changing tabs when focused on a text input field
  lib/views/tabs.dart
  lib/widgets/courseList.dart
  test/widgets/courseList_test.dart
Labels: in progress

#199 Readd Feature to show the reason why there is a time conflict.
  lib/presenter/courseListPresenter.dart
  lib/widgets/courseDetails.dart
Labels: in progress

#192 Tests
  lib/widgets/privacyPage.dart
  test/model/course/course_test.dart
  test/presenter/courseListPresenter_test.dart
  test/utils/nineAPIConsumer_test.dart
  test/views/login_test.dart
  test/views/maps_test.dart
  test/views/settings_test.dart
  test/views/tab_test.dart
  test/widgets/privacyPage_test.dart
  test/widgets/timeTableItem_test.dart
Labels: low prio, testing

#200 last minute aesthetic improvements throughout the app
  lib/main.dart
  lib/model/course/course.dart
  lib/presenter/courseListPresenter.dart
  lib/utils/staticVariables.dart
  lib/views/schedule.dart
  lib/views/tabs.dart
  lib/views/takenCourses.dart
  lib/widgets/courseList.dart
  test/views/tab_test.dart
Labels: in progress

#209 fix momentary crash, making timetable widget stateless
  lib/views/schedule.dart
  lib/views/tabs.dart
Labels: in progress

#211 add nineAPIConsumer internet test
  test/utils/nineAPIConsumer_test.dart
Labels: in progress

#216 Fix crash on filter when logging onto the courseList page with no favorites
  lib/model/course/course.dart
  lib/widgets/courseList.dart
Labels: in progress

#220 Usermetrics
  lib/main.dart
  lib/utils/analytics.dart
  lib/views/login.dart
  lib/views/maps.dart
  lib/views/schedule.dart
  lib/views/settings.dart
  lib/views/start.dart
  lib/views/tabs.dart
  lib/widgets/courseList.dart
  lib/widgets/courseListItem.dart
  lib/widgets/privacyPage.dart
Labels: in progress

#219 only adding the configuration file for firebase
  ios/GoogleService-Info.plist
Labels: in progress

#221 Bugfix: easiest fix for #217
  lib/model/user/user.dart
Labels: in progress

#223 Update Readme to include project homepage
  README.md
Labels: in progress

#222 Bugfix: Unvalid Credentials after sending wrong user data
  lib/views/login.dart
Labels: in progress

#226 New Images and App Name Change
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  res/images/AppLogo.psd
  res/images/HM_1024_500.png
  res/images/HM_1024_500.psd
  res/images/hm_app_icon.png
Labels: in progress

#227 Bugfix: remove mock data
  android/app/build.gradle
  android/app/google-services.json
  lib/presenter/courseListPresenter.dart
  test/presenter/courseListPresenter_test.dart
  test/views/schedule_test.dart
  test/widgets/courseDetails_test.dart
  test/widgets/courseListItem_test.dart
  test/widgets/courseList_test.dart
Labels: in progress

#228 Feature: keep user logged in
  lib/views/login.dart
  lib/views/settings.dart
  lib/views/start.dart
Labels: in progress

#229 Feature: use html view on course details page
  lib/utils/cieStyle.dart
  lib/utils/staticVariables.dart
  lib/widgets/courseDetails.dart
  pubspec.yaml
Labels: in progress

#230 Feature: changed color of login spinner
  lib/generic/genericIcon.dart
Labels: in progress

#231 Remove remaining Mock data from Prod.
  lib/presenter/courseListPresenter.dart
Labels: in progress

#234 Removed dart warnings + Code formatting
  lib/generic/genericAlert.dart
  lib/main.dart
  lib/model/course/course.dart
  lib/model/course/courses_mock.dart
  lib/model/course/details/correlation.dart
  lib/model/course/details/date.dart
  lib/model/course/details/lecturer.dart
  lib/model/user/currentUser_prod.dart
  lib/model/user/user.dart
  lib/presenter/courseListPresenter.dart
  lib/presenter/currentUserPresenter.dart
  lib/utils/analytics.dart
  lib/views/maps.dart
  lib/views/schedule.dart
  lib/views/tabs.dart
  lib/views/takenCourses.dart
  lib/widgets/courseList.dart
  lib/widgets/courseListItem.dart
  lib/widgets/privacyPage.dart
  lib/widgets/timeTableItem.dart
  test/di/course_di_test.dart
  test/generic/genericIcon_test.dart
  test/main_test.dart
  test/model/course/course_test.dart
  test/model/course/courses_mock_test.dart
  test/model/course/details/date_test.dart
  test/model/course/details/room_test.dart
  test/model/user/user_test.dart
  test/presenter/courseListPresenter_test.dart
  test/utils/nineAPIConsumer_test.dart
  test/views/login_test.dart
  test/views/maps_test.dart
  test/views/settings_test.dart
  test/views/tab_test.dart
  test/widgets/courseDetails_test.dart
  test/widgets/courseListItem_test.dart
  test/widgets/courseList_test.dart
  test/widgets/privacyPage_test.dart
  test/widgets/timeTableItem_test.dart
  test_driver/startToTabs.dart
Labels: in progress

#235 Tests
  test/generic/genericIcon_test.dart
  test/model/course/course_test.dart
  test/model/course/details/room_test.dart
  test/model/user/user_test.dart
  test/utils/routes_test.dart
Labels: in progress

#233 Feature: opt out user metrics
  lib/generic/genericAlert.dart
  lib/utils/analytics.dart
  lib/views/login.dart
  lib/views/settings.dart
  lib/views/start.dart
  lib/views/tabs.dart
  test/main_test.dart
  test/views/start_test.dart
Labels: in progress

#238 Bugfix: show courses in all departments + small screens
  lib/model/course/course.dart
  lib/presenter/courseListPresenter.dart
  lib/presenter/currentUserPresenter.dart
  lib/utils/cieStyle.dart
  lib/widgets/courseDetails.dart
  lib/widgets/courseList.dart
  lib/widgets/courseListItem.dart
  lib/widgets/prevCourseListItem.dart
  lib/widgets/timeTableItem.dart
  test/model/course/course_test.dart
  test/model/course/courses_mock_test.dart
  test/presenter/courseListPresenter_test.dart
  test/presenter/currentUserPresenter_test.dart
Labels: in progress

#243 Show help in courses list
  lib/generic/genericIcon.dart
  lib/generic/genericShowInstruction.dart
  lib/presenter/courseListPresenter.dart
  lib/utils/cieStyle.dart
  lib/utils/staticVariables.dart
  lib/views/settings.dart
  lib/widgets/courseDetails.dart
  lib/widgets/courseList.dart
  pubspec.yaml
  res/images/AppLogo_45Transparent.png
  res/images/AppLogo_45Transparent.psd
Labels: in progress

#244 added data for release of version 2 (1.1)
  android/app/build.gradle
  android/app/google-services.json
Labels: in progress

#245 Tests
  test/generic/genericShowInstruction_test.dart
  test/model/course/course_test.dart
  test/views/settings_test.dart
Labels: in progress

#254 Add filter all departments function + Some refactoring
  lib/widgets/courseList.dart
Labels: in progress

#255 Bugfixes: mixed
  lib/generic/genericShowInstruction.dart
  lib/utils/staticVariables.dart
  lib/views/start.dart
  lib/widgets/privacyPage.dart
  test/generic/genericShowInstruction_test.dart
Labels: in progress

#256 use lower case logic in courseList to avoid case sensitive search
  lib/widgets/courseList.dart
Labels: in progress

#258 Tests
  test/model/course/course_test.dart
  test/model/user/user_test.dart
Labels: in progress

#260 Code Clean up
  lib/generic/genericAlert.dart
  lib/generic/genericIcon.dart
  lib/generic/genericShowInstruction.dart
  lib/presenter/courseListPresenter.dart
  lib/utils/cieStyle.dart
  lib/utils/staticVariables.dart
  lib/views/login.dart
  lib/views/settings.dart
  lib/widgets/courseList.dart
  test/generic/genericIcon_test.dart
  test/generic/genericShowInstruction_test.dart
  test/main_test.dart
  test/model/course/course_test.dart
  test/model/course/details/room_test.dart
  test/presenter/courseListPresenter_test.dart
  test/presenter/currentUserPresenter_test.dart
  test/utils/routes_test.dart
  test/views/settings_test.dart
  test/widgets/privacyPage_test.dart
Labels: in progress

#257 Make App ready for Release 3
  android/app/build.gradle
  lib/widgets/privacyPage.dart
Labels: in progress

#262 Fix the empty schedule on first bootup
  lib/views/schedule.dart
  lib/views/tabs.dart
Labels: in progress
